# Generated by Django 3.2 on 2022-06-30 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime_created', models.DateTimeField(auto_now_add=True)),
                ('dtime_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime_created', models.DateTimeField(auto_now_add=True)),
                ('dtime_updated', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('base_curr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_currency_rate_records', to='api_caller.currency', verbose_name='Currency (Base)')),
                ('curr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_rate_records', to='api_caller.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'currency rate record',
                'verbose_name_plural': 'currency rate records',
            },
        ),
    ]
