# Generated by Django 3.2 on 2022-06-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_caller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField()),
                ('rate', models.FloatField()),
                ('base_curr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currencyraterecord_base_currency', to='api_caller.currency')),
                ('curr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currencyraterecord_currency', to='api_caller.currency')),
            ],
        ),
        migrations.DeleteModel(
            name='RateRecord',
        ),
    ]
