# Generated by Django 3.2 on 2022-06-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_caller', '0003_auto_20220624_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyraterecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
