# Generated by Django 3.2 on 2022-06-24 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_caller', '0004_alter_currencyraterecord_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyraterecord',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='currencyraterecord',
            name='timedate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
