# Generated by Django 3.2 on 2022-06-28 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_caller', '0005_auto_20220624_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyraterecord',
            old_name='timedate',
            new_name='dtime_created',
        ),
        migrations.AddField(
            model_name='currency',
            name='dtime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='dtime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='currencyraterecord',
            name='dtime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
