name: Pre deploy checks
on:
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.4'
          architecture: 'x64'
      - name: Get changed files
        id: changed-files
        with:
          separator: ' '
        uses: tj-actions/changed-files@v23
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: ${{ steps.changed-files.outputs.all_changed_files }}
          max-line-length: '79'
          plugins: 'flake8-bugbear==22.1.11'
          args: '--max-complexity 8'
          exclude: '.github'
